
import java.awt.Button;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class collegeappnext2 extends java.applet.Applet {
    Button c1,c2,c3,c4,c5,c6 ;

    /**
     * Initializes the applet collegeappnext2
     */
    public void init() {
        try {
            
		 Button c1= new Button("Amity School Of Engineering and Technology");
		 Button c2=new Button("bharti Vidyapeeth Institute Of Technology");
		 Button c3=new Button("Guru Teg Bahadur institute of Technology");
                 Button c4=new Button("Maharaja Agrasen Institute of Technology");
                 Button c5=new Button("Maharaja Surajmal Institute of Technology");
                 Button c6=new Button("University school Of engineering and Technology");
		 add(c1);
		 add(c2);
                 add(c3);
                 add(c4);
                 add(c5);
                 add(c6);
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
